server.port=8084

# User service local url
user.service.url=http://localhost:8083

# OAuth config (set your client id/secret in .env)
oauth.github.client-id=${GITHUB_CLIENT_ID}
oauth.github.client-secret=${GITHUB_CLIENT_SECRET}
oauth.github.token-uri=https://github.com/login/oauth/access_token
oauth.github.user-api-uri=https://api.github.com/user
oauth.github.user-emails-api-uri=https://api.github.com/user/emails

# Google OAuth
oauth.google.client-id=${GOOGLE_CLIENT_ID}
oauth.google.client-secret=${GOOGLE_CLIENT_SECRET}
oauth.google.token-uri=https://oauth2.googleapis.com/token
oauth.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-seconds=${JWT_EXP}