spring.application.name = auth-service

# common logging & actuator
management.endpoints.web.exposure.include=health,info

# Feign will use this default, override in env/profiles
user.service.url=http://localhost:8083