server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
       - id: auth-service
         uri: http://localhost:8084
         predicates:
           - Path=/api/auth/**
         filters:
           - RemoveRequestHeader=Cookie

       - id: user-service
         uri: http://localhost:8083
         predicates:
           - Path=/api/user/**
         filters:
           - RemoveRequestHeader=Cookie

       - id: question-service
         uri: http://localhost:8082
         predicates:
           - Path=/api/questions/**
         filters:
           - RemoveRequestHeader=Cookie

       - id: exam-service
         uri: http://localhost:8081
         predicates:
           - Path=/api/exams/**
         filters:
           - RemoveRequestHeader=Cookie

jwt:
  secret: ${JWT_SECRET}