server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8084
          predicates:
            - Path=/api/auth/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=/api/user/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: exam-service
          uri: http://exam-service:8081
          predicates:
            - Path=/api/exams/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: question-service
          uri: http://question-service:8082
          predicates:
            - Path=/api/questions/**
          filters:
            - RemoveRequestHeader=Cookie

jwt:
  secret: ${JWT_SECRET}
